const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.NinePatch,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Timer,
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.ppstudio_newgroundsio_plugin,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Date,
		C3.Plugins.Json,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Dictionary,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Bullet,
		C3.Plugins.sliderbar,
		C3.Behaviors.solid,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.List,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.ImageWidth,
		C3.Plugins.TiledBg.Acts.AddChild,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Browser.Acts.Reload,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.regexmatchcount,
		C3.Plugins.Browser.Exps.URL,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.List.Acts.SetVisible,
		C3.Plugins.sliderbar.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Exps.log10,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Spritefont2.Exps.TextWidth,
		C3.Plugins.Spritefont2.Exps.TextHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.TiledBg.Exps.UID,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetImageScaleX,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceWidth,
		C3.Plugins.TiledBg.Acts.SetImageScaleY,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceHeight,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.Count,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.TiledBg.Acts.LoadURL,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.TiledBg.Cnds.OnURLLoaded,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.TiledBg.Cnds.PickByUID,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Browser.Exps.ExecJS,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnError,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.Dictionary.Cnds.IsEmpty,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.TypeScriptInEvents.Global_Event66_Act12,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Json.Exps.Path,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareChildCount,
		C3.Plugins.DrawingCanvas.Acts.SetInstanceVar,
		C3.Plugins.DrawingCanvas.Acts.SetVisible,
		C3.Plugins.DrawingCanvas.Acts.SetResolutionMode,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.ForEach,
		C3.TypeScriptInEvents.Global_Event78_Act1,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.RemoveEffects,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Audio.Acts.AddFilterEffect,
		C3.Plugins.Audio.Acts.SetEffectParameter,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Acts.AppendText,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Acts.Reverse,
		C3.TypeScriptInEvents.Plaza_Event19_Act1,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Acts.Delete,
		C3.TypeScriptInEvents.Plaza_Event60_Act1,
		C3.TypeScriptInEvents.Plaza_Event62_Act2,
		C3.Plugins.DrawingCanvas.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.Json.Acts.DeleteKey,
		C3.TypeScriptInEvents.Creator_Event38_Act1,
		C3.Plugins.TextBox.Cnds.CompareInstanceVar,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.List.Cnds.CompareInstanceVar,
		C3.Plugins.sliderbar.Cnds.CompareInstanceVar,
		C3.TypeScriptInEvents.Creator_Event112_Act1,
		C3.Plugins.List.Acts.Clear,
		C3.TypeScriptInEvents.Creator_Event115_Act3,
		C3.Plugins.List.Cnds.OnSelectionChanged,
		C3.TypeScriptInEvents.Creator_Event116_Act1,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.sliderbar.Cnds.OnChanged,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Plugins.System.Exps.zeropad,
		C3.TypeScriptInEvents.Creator_Event139_Act1,
		C3.TypeScriptInEvents.Creator_Event141_Act1,
		C3.TypeScriptInEvents.Creator_Event144_Act2,
		C3.TypeScriptInEvents.Creator_Event145_Act1,
		C3.TypeScriptInEvents.Creator_Event148_Act2,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.TypeScriptInEvents.Server_Event4_Act3,
		C3.TypeScriptInEvents.Server_Event9_Act1,
		C3.TypeScriptInEvents.Server_Event28_Act1,
		C3.Plugins.ppstudio_newgroundsio_plugin.Cnds.IsLoggedIn,
		C3.Plugins.ppstudio_newgroundsio_plugin.Acts.Logout,
		C3.Plugins.ppstudio_newgroundsio_plugin.Acts.Login,
		C3.TypeScriptInEvents.Server_Event34_Act2,
		C3.TypeScriptInEvents.Server_Event35_Act2,
		C3.Plugins.ppstudio_newgroundsio_plugin.Cnds.IsReady,
		C3.Plugins.ppstudio_newgroundsio_plugin.Cnds.OnLogin,
		C3.Plugins.ppstudio_newgroundsio_plugin.Exps.SessionID,
		C3.TypeScriptInEvents.Server_Event39_Act2,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Date.Exps.GetHours,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Date.Exps.GetSeconds,
		C3.Plugins.Date.Exps.GetMinutes
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{LoaderBase: 0},
	{maxWidth: 0},
	{Timer: 0},
	{LoaderBar: 0},
	{LoaderBackground: 0},
	{AJAX: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{NGIO: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{Date: 0},
	{JSON: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{SaveFile: 0},
	{TransitionSquareList: 0},
	{TransitionSquare: 0},
	{ScumDog: 0},
	{type: 0},
	{Text: 0},
	{NavBar: 0},
	{Fade: 0},
	{animation: 0},
	{id: 0},
	{selected: 0},
	{holdable: 0},
	{disabled: 0},
	{valid: 0},
	{Button: 0},
	{ButtonIcon: 0},
	{MenuBackground: 0},
	{Bullet: 0},
	{Logo: 0},
	{SettingsSlider: 0},
	{Solid: 0},
	{Idle: 0},
	{ErrorBackground: 0},
	{part: 0},
	{parentType: 0},
	{parent: 0},
	{total: 0},
	{data: 0},
	{CharacterHead: 0},
	{CharacterPart: 0},
	{CharacterCanvas: 0},
	{Parts: 0},
	{SavedCharacters: 0},
	{Card: 0},
	{UUID: 0},
	{SortedCharacters: 0},
	{InputDropdown: 0},
	{InputName: 0},
	{InputSlider: 0},
	{CreatorBackground: 0},
	{PlazaBackground: 0},
	{DisclaimerBackground: 0},
	{Character: 0},
	{LOADER_maxItems: 0},
	{LOADER_progress: 0},
	{LOADER_clicked: 0},
	{LOADER_error: 0},
	{LOADER_progressOld: 0},
	{error: 0},
	{GAME_init: 0},
	{GAME_load: 0},
	{GAME_mobile: 0},
	{NGIO_onNewgrounds: 0},
	{GAME_idleTimeout: 0},
	{LOAD_saveCharacters: 0},
	{LOAD_saveSettings: 0},
	{LOAD_disclaimer: 0},
	{LOAD_parts: 0},
	{SETTING_volumeSound: 0},
	{SETTING_volumeMusic: 0},
	{SETTING_fullscreen: 0},
	{TRANSITION_running: 0},
	{TRANSITION_movedLayout: 0},
	{parameter: 0},
	{value: 0},
	{layer: 0},
	{visibility: 0},
	{enabled: 0},
	{text: 0},
	{TRANSITION_layout: 0},
	{TRANSITION_squareSize: 0},
	{TRANSITION_squareAmountX: 0},
	{TRANSITION_squareAmountY: 0},
	{TRANSITION_squaresReady: 0},
	{TRANSITION_snapshotReady: 0},
	{TRANSITION_squaresLoaded: 0},
	{layout: 0},
	{x: 0},
	{y: 0},
	{scale: 0},
	{mirrored: 0},
	{PLAZA_maxLocalCharacters: 0},
	{PLAZA_maxPerPage: 0},
	{PLAZA_state: 0},
	{GAME_selectedCharacterIndex: 0},
	{GAME_selectedCharacterType: 0},
	{GAME_selectedCharacterData: 0},
	{state: 0},
	{index: 0},
	{CREATOR_maxPerPage: 0},
	{CREATOR_part: 0},
	{CREATOR_editing: 0},
	{CREATOR_cachedCharacterData: 0},
	{start: 0},
	{created: 0},
	{set: 0},
	{MENU_menu: 0},
	{MENU_overlayMenu: 0},
	{MENU_offset: 0},
	{MENU_clicked: 0},
	{MENU_buttonID: 0},
	{MENU_locked: 0},
	{name: 0},
	{NGIO_sessionID: 0},
	{SERVER_isLoggedIn: 0},
	{SERVER_isAdmin: 0},
	{SERVER_hasUploadedCharacter: 0},
	{SERVER_uploadedCharacterData: 0},
	{SERVER_uploadedCharacterID: 0},
	{SERVER_uploadedCharacterEditable: 0},
	{editable: 0}
];

self.InstanceType = {
	LoaderBase: class extends self.I9PatchInstance {},
	LoaderBar: class extends self.ITiledBackgroundInstance {},
	LoaderBackground: class extends self.ITiledBackgroundInstance {},
	AJAX: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	NGIO: class extends C3.Plugins.ppstudio_newgroundsio_plugin.Instance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Date: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	SaveFile: class extends self.IDictionaryInstance {},
	TransitionSquareList: class extends self.IArrayInstance {},
	TransitionSquare: class extends self.ITiledBackgroundInstance {},
	ScumDog: class extends self.ISpriteInstance {},
	Text: class extends self.ISpriteFontInstance {},
	NavBar: class extends self.ISpriteInstance {},
	Fade: class extends self.ISpriteInstance {},
	Button: class extends self.ISpriteInstance {},
	ButtonIcon: class extends self.ISpriteInstance {},
	MenuBackground: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	SettingsSlider: class extends self.ISliderBarInstance {},
	Idle: class extends self.ISpriteInstance {},
	ErrorBackground: class extends self.I9PatchInstance {},
	CharacterHead: class extends self.ISpriteInstance {},
	CharacterPart: class extends self.ISpriteInstance {},
	CharacterCanvas: class extends self.IDrawingCanvasInstance {},
	Parts: class extends self.IArrayInstance {},
	SavedCharacters: class extends self.IArrayInstance {},
	Card: class extends self.ISpriteInstance {},
	UUID: class extends self.ISpriteFontInstance {},
	SortedCharacters: class extends self.IArrayInstance {},
	InputDropdown: class extends self.IListInstance {},
	InputName: class extends self.ITextInputInstance {},
	InputSlider: class extends self.ISliderBarInstance {},
	CreatorBackground: class extends self.ITiledBackgroundInstance {},
	PlazaBackground: class extends self.ITiledBackgroundInstance {},
	DisclaimerBackground: class extends self.ITiledBackgroundInstance {},
	Character: class extends self.ISpriteInstance {}
}